name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Compose
      run: |
        docker-compose --version || sudo apt-get update && sudo apt-get install -y docker-compose

    - name: Display flask-app files
      run: |
        echo "Listing project files..."
        ls -R

    - name: Build and display flask-app logs simultaneously
      run: |
        docker-compose up --build --force-recreate --remove-orphans &  # Lance la construction en arrière-plan
        docker-compose logs -f flask-app  # Affiche les logs simultanément

    - name: Tear down services
      run: |
        docker-compose down