name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Compose
      run: |
        docker-compose --version || sudo apt-get update && sudo apt-get install -y docker-compose

    - name: Build and start services
      run: |
        docker-compose up --build -d

    - name: Display flask-app logs
      run: |
        docker-compose logs flask-app

    - name: Tear down services
      if: always()
      run: |
        docker-compose down